runtime: python27
api_version: 1
threadsafe: true

handlers:
  # Serve the pre-rendered HTML files for server requests
  - url: /
    static_files: dist/revspeed-app/server/index.server.html
    upload: dist/revspeed-app/server/index.server.html

  # Serve static assets for server requests
  - url: /(.*\.(gif|png|jpg|ico|js|css|swf|xml|json))$
    static_files: dist/revspeed-app/server/\1
    upload: dist/revspeed-app/server/(.*\.(svg|gif|png|jpg|ico|js|css|swf|xml|json))$

  # Serve dynamic requests to the server folder
  - url: /.*
    script: auto

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json  
  - ^(.*/)?.*\.md$  
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
