runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: revspeed-app/index.html
    upload: revspeed-app/index.html
  - url: /
    static_dir: revspeed-app

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json  
  - ^(.*/)?.*\.md$  
  - ^(.*/)?.*\.yaml$
  - ^LICENSE