apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-gke-sample
  labels:
    app: angular-gke-sample
spec:
  replicas: 1
  selector:
    matchLabels:
        app: angular-gke-sample
  template:
    metadata:
      labels:
        app: angular-gke-sample
    spec:
      containers:
        - name: angular-gke-sample
          image: gcr.io/revdep/angular-gke-sample:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-image-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-gke-sample
  name: angular-gke-sample
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4200
  selector:
    app: angular-gke-sample
  type: LoadBalancer