name: Angular GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GET_GKE_CRED_PROJECT }}
  GKE_CLUSTER: angular-gke-sample
  GKE_ZONE: us-central1
  IMAGE: angular-gke-sample
  TAG: 0.0.1

jobs:
  build-and-deploy:
    name: Build and Deploy Angular App to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          check-latest: true

      - name: Install Angular CLI and dependencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Build Angular App
        run: npm run build

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
          project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.TAG }} .

      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml
